CREATE TABLE [dbo].[ComputerInfo]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Model] NVARCHAR(100) NOT NULL, 
    [OS] NVARCHAR(100) NULL, 
    [SerialNumber] NVARCHAR(50) NULL,
	[CPU] NVARCHAR(100) NULL,
	[CPUCores] NVARCHAR(50) NULL,
	[RAM] NVARCHAR(100) NULL,
	[DiskType] NVARCHAR(50) NULL,
	[DiskSize] NVARCHAR(100) NULL,
	[GFX] NVARCHAR(100) NULL,
	[TeamViewerId] NVARCHAR(50) NULL,
    [LastAlive] DATETIME NOT NULL
)